version: "3.6"

services:
  postgres_test_db:
    container_name: postgres_test_db
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
