__all__ = [
    "FAKE_USERS",
    "TEST_BASE_SERVICE_GET_BY_QUERY_ONE_OR_NONE_PARAMS",
    "TEST_BASE_SERVICE_GET_BY_QUERY_ALL_PARAMS",
    "TEST_BASE_SERVICE_UPDATE_ONE_BY_ID_PARAMS",
    "TEST_BASE_SERVICE_DELETE_BY_QUERY_PARAMS",
    "TEST_SQLALCHEMY_REPOSITORY_GET_BY_QUERY_ONE_OR_NONE_PARAMS",
    "TEST_SQLALCHEMY_REPOSITORY_GET_BY_QUERY_ALL_PARAMS",
    "TEST_SQLALCHEMY_REPOSITORY_UPDATE_ONE_BY_ID_PARAMS",
    "TEST_SQLALCHEMY_REPOSITORY_DELETE_BY_QUERY_PARAMS",
]

from .users import FAKE_USERS
from .fake_params import *
